### ISSUE TITLE
Experiment with Whatsapp Twilio API 

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#285]
## Description

Users of the website want to be able to receive notifications through WhatsApp

## Learning objectives

- Using Twilio WhatsApp Api 

## Todo

- [x] Determine if django-twilio package is suitable for whatsapp message sending 
- [x] Create twilio account and get relevant credentials 
- [x] Create test endpoint for testing notifs
- [x] Create helper function/class with sample template to help with sending notifications through endpoint

## Useful links

- https://www.twilio.com/whatsapp

- https://www.twilio.com/blog/receive-whatsapp-messages-python-django-twilio
