### ISSUE TITLE
Zubhub Open-Source Readiness

### ISSUE THREAD

**Issue by NdibeRaymond** [unstructuredstudio/zubhub#291]
## Description
There is a need to prepare for the eventual open-sourcing of this project. Below are the list of things I can personal think of that should be done go get there. Please feel free to add more items to this list: 

## TODOs

- [x] Publish an updated version of the database schema image.
- [x] Publish an updated readme on how to get the project running on your local machine.
- [ ] ~Deliberate more on how to handle deployments (e.g. moving all CI/CD setup and scripts to a different repository, etc)~
- [x] Start working on issue #290 
- [x] Update ZubHub page on Unstructured website with Documentation and Source code links
- [x] Add LICENSE
- [x] Make Feature Roadmap public on the Wiki

**Comment by NdibeRaymond** [comment]
Many of the tasks here have been completed, however who should leave it open so we don't function the last task that is still open

**Comment by tuxology** [comment]
Maybe we create another task for Deployments separately since it will have multiple sub-tasks and then keep it open @NdibeRaymond ? I'll create a separate task and get back here

**Comment by tuxology** [comment]
I'm closing this and creating another task later for deployment separation
