### ISSUE TITLE
Notification Dropdown

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#298]
## Description

Add the outer portion of the Notifications Dropdown.

Context: This is where users can see a list of their notifications. 

## Todo

- [x] Add Bell Icon
- [x] Add dropdown
- [x] Add buttons for All and Unread
- [x] Divide dropdown into New and Earlier
- [x] Adapt for both mobile and web

## Useful links

- Mobile Figma Design: https://www.figma.com/file/rdoLGoH5vfFBfqV11lgOyw/ZubHub-Mobile?node-id=0%3A1
- Web Figma: https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub-Web?node-id=0%3A1

**Comment by NdibeRaymond** [comment]
The figma files are locked. can somebody help? @ajain1921 and @AndrewLester

**Comment by ghost** [comment]
> The figma files are locked. can somebody help? @ajain1921 and @AndrewLester

@NdibeRaymond Try this link:
https://www.figma.com/team_invite/redeem/EwZTegqxTQOoLUqWsUpT8a
