### ISSUE TITLE
Notification Item

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#299]
## Description

Create a component for each Notification in the Notification Center

Context: This is where users can see the information regarding their notification

## Todo

- [x] Create a component that can accept things like message, profile pic, whether it was viewed so that it can be called from a map function
- [x] Redirect based on link when clicked on
- [x] Adapt for mobile

## Useful links

- Mobile Figma Design: https://www.figma.com/file/rdoLGoH5vfFBfqV11lgOyw/ZubHub-Mobile?node-id=0%3A1
- Web Figma: https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub-Web?node-id=0%3A1

**Comment by yaya-usman** [comment]
@ajain1921 can i be assigned this as well?
