### ISSUE TITLE
Add autosaving functionality

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#322]
## Description

Add autosaving functionality to the Create Project form.

Context: Due to internet concerns, we want to autosave the user's form responses for the Create Project form. 

## Learning objectives

- Formik
- Debouncing

## Todo

- [ ] Determine when to trigger a save
- [ ] Display a message in top right with current date and time (look at designs) upon saving
- [ ] Determine how videos/images will be handled

## Useful links

- https://itnext.io/formik-introduction-autosave-react-19d4c15cfb90

**Comment by srish** [comment]
This was addressed in recent enhancements related to project creation.
