### ISSUE TITLE
Integrate helper functions with notification triggers

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#323]
## Description

Use Zora's helper function (#306) and Andrew's function (#316) in the notification triggers (ex. adding a comment, following someone) to send a notification and add to the Notifications model.

## Learning objectives

- Django REST framework
- Templates

## Todo

- [ ] Edit `send_notification`:
  - [ ] Remove template_name, replace with notification type. Get template names from notification types
  - [ ] Based on notification type, create link parameter and pass into `push_notification`.
  - [ ] Add source parameter to `send_notification` method.
  - [ ] Add override parameter to send_notification to turn off certain contact methods.
- [ ] Add helper functions to each notification trigger (look at notion for complete list)
- [ ] Modify ```send_notification``` to accept the correct parameters for ```push_notification```
- [ ] Add basic templates for each notification type

## Useful links

- https://www.notion.so/h4iuiuc/What-Creates-Notifications-9b07d395afd8436fb8a964025064575b

**Comment by tuxology** [comment]
@ajain1921 This does seem like much of this is done. If yes, can we close this?

**Comment by tuxology** [comment]
This has been resolved so closing 🎉
