### ISSUE TITLE
Drafts Tab and Page

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#334]
## Description

On the profile page, add a drafts and projects tab so that users can view both. They should operate in the same way except one should redirect to projects and the other to drafts.

## Learning objectives
- React
- Material UI

## Todo

- [ ] Add tabbed component
- [ ] Create Drafts page
- [ ] Add support for both mobile and web

## Useful links

- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub?node-id=0%3A1
