### ISSUE TITLE
Improve search functionality

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#359]
## Description

Improve search functionality by adding a filter to choose what to search over: projects, tags, or creators.

Context: Currently, the search bar searches through projects and creators automatically and displays the results with a creators and projects tab. To make it clearer for the user, we're adding the ability to choose what to search over. 

## Learning objectives

- React
- Django REST Framework

## Todo
- [x] Add filter with dropdown options to search bar (see designs)
- [x] Remove current search result system with tab for creators and projects (see designs)
- [x] Call appropriate search endpoint (tags, creators, projects) and display results

## Useful links

- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub?node-id=0%3A1
