### ISSUE TITLE
Notification Bugs

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#381]
## Description

There's a few minor bugs left in the notification implementation to work out.

## Learning objectives
- Django REST Framework
- React

## Todo

- [x] If someone performs an action, undoes it, and redoes it, the backend interprets it as grouped notifications. 
- [x] After clicking a notification the panel should disappear.
- [ ] If you open the mobile notification panel on a project with a video the video shows above the panel. (same applies for floating action buttons)
- [x] Grouped notifications from following someone should redirect to the person who was followed.
- [x] You shouldn't need to refresh the page for notification updates to appear. They should be triggered upon opening the notification panel.

**Comment by pro-coder-devshekhar** [comment]
@ajain1921 Can you please assign me this issue?

**Comment by AndrewLester** [comment]
For the todos:
1. Are we considering removing notifications from actions that are undone as the solution for this?
2. No questions
3. No questions
4. Isn't the person who was followed just yourself?
5. No questions

**Comment by srish** [comment]
@ajain1921 @AndrewLester I recently tried testing the notification feature (with two accounts), and it is not working for me. I tried by leaving a comment on a user's project and I don't see any notification for this activity. Furthermore, when I add a comment, I get an error message: "..Sorry it looks like we have hit a snag, please try again later".

**Comment by ghost** [comment]
@srish I think suchakra was having similar issues with his account before as well but we weren't able to reproduce them with the accounts that we're using. I'm thinking it might have something to do with the fact that the accounts are Staff accounts. Are both the accounts that you tried Staff accounts or is there anything different about them compared to normal accounts that a user might create?

**Comment by srish** [comment]
> @srish I think suchakra was having similar issues with his account before as well but we weren't able to reproduce them with the accounts that we're using. I'm thinking it might have something to do with the fact that the accounts are Staff accounts. Are both the accounts that you tried Staff accounts or is there anything different about them compared to normal accounts that a user might create?

@ajain1921 Yes, I tested with both staff accounts.

**Comment by ghost** [comment]
@srish Ok interesting. I'm guessing this issue is specifically for Staff accounts then, which we didn't test the feature with. We'll try to have a fix ready for it soon.

**Comment by srish** [comment]
@ajain1921 Another thing that I have noticed is that when I try to clap on a project, I get an error "hmm, seems like we could not delete your project.. try again later," and in the case of bookmarking, I get an error "looks like you have hit a snag..". I wonder if this also has to do with a bug in the notifications system right now, as I noticed the same issue when I commented on a project. Let me know if these errors don't have anything to do with the notifications system, and I will file them separately as bugs.

**Comment by ghost** [comment]
@srish I think that all has to do with notifications because events like bookmarking and clapping are triggers for notifications.

**Comment by tuxology** [comment]
Here are the attached logs from production backend when submitting comments. The comments system is also broken because of this it seems:

```
Internal Server Error: /api/projects/0848243c-5381-45f3-bacb-e60c58fdda73/add-comment/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/zubhub_backend/zubhub/projects/views.py", line 453, in create
    send_notification(
  File "/zubhub_backend/zubhub/creators/utils.py", line 395, in send_notification
    user_setting = Setting.objects.get(creator=user)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
creators.models.Setting.DoesNotExist: Setting matching query does not exist.
10.0.0.2 - - [26/May/2022:21:27:12 +0000] "POST /api/projects/0848243c-5381-45f3-bacb-e60c58fdda73/add-comment/ HTTP/1.1" 500 145 "https://zubhub.unstructured.studio/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
10.0.0.2 - - [26/May/2022:21:28:07 +0000] "GET /api/notifications/?page=1 HTTP/1.1" 200 52 "https://zubhub.unstructured.studio/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
```

**Comment by tuxology** [comment]
This issue has been resolved. We did not track it but @NdibeRaymond helped in fixing this! 🎉
