### ISSUE TITLE
Mobile Sharing

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#398]
## Description

Add share button to mobile view to trigger native sharing menu. 

## Learning objectives

- React
- Webshare API

## Todo

- [ ] Add share button
- [ ] Connect share button to native menu
- [ ] Autofill when applicable

## Useful links
- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub
