### ISSUE TITLE
Add Recommended Projects Bar

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#418]
## Description

Add bar to showcase the recommended projects for a project on the project page. 

## Learning objectives

- React
- CSS

## Todo

- [x] Create container component to house the recommended projects
- [x] Use test projects to ensure it looks right
- [x] Adapt for mobile and web
