### ISSUE TITLE
Add Project Unpublished Backend Support

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#428]
## Description

Add backend support for project unpublishing.

## Learning objectives

- Django REST Framework
- PostgreSQL

## Todo

- [ ] Add type to PublishingRule that indicates unpublished
- [ ] Add endpoint that will unpublish a project and notify the user
- [ ] Add method of storing unpublish reasons
