### ISSUE TITLE
create a new view to display list of activities .

### ISSUE THREAD

**Issue by souad988** [unstructuredstudio/zubhub#500]
create a new view to display list of activities .

## Todo

- [x] Create activities.js with basic component.
- [x] Add  root to activities on app.js.
- [x] Add activities button in home header to redirect user to activities view.
- [x] Create activities initial state and reducer and Update combineReducers to include activitiesReducer.
- [x] Create a genereric activities json object list to use until creating activities backend.

**Comment by srish** [comment]
This was addressed as part of activities integration.
