### ISSUE TITLE
Create activity card component.

### ISSUE THREAD

**Issue by souad988** [unstructuredstudio/zubhub#507]
## Todo

- [x] Create Activity component.
- [x] Create projects count Icon 
- [x] Add activity creator link and Image 
- [x] Display activity tags 
- [ ] Follow figma  [design](https://www.figma.com/file/jEy3xfgLKa7VGaJgf4Bwmx/create-activity-button?node-id=73%3A121)
- [ ] Wrap activity card with a Link to activityDetails view .
