### ISSUE TITLE
Add badges feature on the user's profile

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#512]
## Todo

- [x] #513
- [x]  Call the API  and handle the response appropriately
- [x] #517
- [x]  Adding reusable stying component to the badges 
- [x]  Add styling to make the look similar to [figma](https://www.figma.com/file/qwDHghGfIPy9740jLylPwH/figma-mockup_1.0?node-id=0%3A1) design

**Comment by tuxology** [comment]
Closing this since its done as part of #518
